Repository nvim-treesitter/nvim-treesitter, pull requests merged in 2022-01, with the labels that each got.

#2319 ci: use stable tag for latest nvim release
  .github/workflows/check-query-files-and-compilation.yml
  .github/workflows/tests.yml
  .github/workflows/update-parsers-pr.yml
  .github/workflows/update-readme.yml
Labels: CI

#2326 highlights(r): change groups priority
  queries/r/highlights.scm
Labels: highlights

#2330 ci: drop windows+clang
  .github/workflows/check-query-files-and-compilation.yml
Labels: CI

#2328 feat: specify ABI version for generate on newer tree-sitter CLI
  lua/nvim-treesitter/health.lua
  lua/nvim-treesitter/install.lua
  lua/nvim-treesitter/utils.lua
Labels: enhancement, CI

#2341 fix: bump phpdoc parser to 0.0.6
  lockfile.json
Labels: parser

#2379 chore: run parser update at least daily
  .github/workflows/update-parsers-pr.yml
Labels: CI
