Repository nvim-treesitter/nvim-treesitter, pull requests merged in 2024-01, with the labels that each got.

#5876 feat: add the php_only parser included in tree-sitter-php
  README.md
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/php/folds.scm
  queries/php/highlights.scm
  queries/php/indents.scm
  queries/php/injections.scm
  queries/php/locals.scm
  queries/php_only/folds.scm
  queries/php_only/highlights.scm
  queries/php_only/indents.scm
  queries/php_only/injections.scm
  queries/php_only/locals.scm
Labels: new-language

#5943 fix(comments)!: consolidate note captures
  CONTRIBUTING.md
  queries/comment/highlights.scm
  queries/gitcommit/highlights.scm
  queries/vimdoc/highlights.scm
Labels: breaking change

#5948 feat: add the zathurarc parser included in tree-sitter-zathurarc
  README.md
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/zathurarc/highlights.scm
  queries/zathurarc/injections.scm
Labels: new-language

#5755 Add tree-sitter-disassembly
  README.md
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/disassembly/highlights.scm
  queries/disassembly/injections.scm
Labels: new-language

#5594 feat(gnuplot): added gnuplot parser and queries
  README.md
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/gnuplot/highlights.scm
  queries/gnuplot/injections.scm
Labels: new-language

#5779 feat(angular)!: switch to parser supporting v17
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/angular/folds.scm
  queries/angular/highlights.scm
  queries/angular/indents.scm
  queries/angular/injections.scm
  queries/angular/locals.scm
  queries/ecma/injections.scm
  queries/html_tags/injections.scm
Labels: breaking change, new-language

#5957 feat(groovy)!: switch to more complete parser
  README.md
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/groovy/folds.scm
  queries/groovy/highlights.scm
  queries/groovy/indents.scm
  queries/groovy/injections.scm
  queries/groovy/locals.scm
Labels: breaking change, new-language
