Repository nvim-treesitter/nvim-treesitter, pull requests merged in 2024-02, with the labels that each got.

#6043 feat(faust): add new parser tree-sitter-faust
  README.md
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/faust/highlights.scm
  queries/faust/injections.scm
Labels: new-language

#6058 feat(readline): add parser tree-sitter-readline
  README.md
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/readline/folds.scm
  queries/readline/highlights.scm
  queries/readline/indents.scm
  queries/readline/injections.scm
Labels: new-language

#5988 feat(d)!: switch upstream parser to `gdamore/tree-sitter-d`
  README.md
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/d/folds.scm
  queries/d/highlights.scm
  queries/d/indents.scm
  queries/d/injections.scm
  queries/d/locals.scm
Labels: breaking change, new-language

#5852 feat: add hyprlang parser & queries
  README.md
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/hyprlang/folds.scm
  queries/hyprlang/highlights.scm
  queries/hyprlang/indents.scm
Labels: new-language

#6027 feat(slint)!: change to the official parser
  README.md
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/rust/injections.scm
  queries/slint/folds.scm
  queries/slint/highlights.scm
  queries/slint/indents.scm
  queries/slint/injections.scm
  queries/slint/locals.scm
Labels: breaking change, new-language

#6067 feat(tcl): add parser and queries
  README.md
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/tcl/folds.scm
  queries/tcl/highlights.scm
  queries/tcl/indents.scm
Labels: new language

#6084 feat: add the hlsplaylist parser
  README.md
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/hlsplaylist/highlights.scm
  queries/hlsplaylist/injections.scm
Labels: new language

#6095 feat: add the muttrc parser
  README.md
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/muttrc/highlights.scm
  queries/muttrc/injections.scm
Labels: new language

#6131 fix(bass): revert to upstream parser
  lockfile.json
  lua/nvim-treesitter/parsers.lua
Labels: new language

#6140 feat(svelte)!: switch upstream parser
  README.md
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/svelte/folds.scm
  queries/svelte/highlights.scm
  queries/svelte/indents.scm
  queries/svelte/injections.scm
  queries/svelte/locals.scm
Labels: breaking change, new language

#6141 feat: add the tmux parser
  README.md
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/tmux/highlights.scm
  queries/tmux/injections.scm
Labels: new language

#6132 feat(fennel)! change parser and update queries
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/fennel/folds.scm
  queries/fennel/highlights.scm
  queries/fennel/injections.scm
  queries/fennel/locals.scm
Labels: breaking change, new language

#6166 Add .fidl support
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/fidl/folds.scm
  queries/fidl/highlights.scm
  queries/fidl/injections.scm
Labels: new language

#6153 feat: add support for gdshader
  README.md
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/gdshader/highlights.scm
  queries/gdshader/injections.scm
Labels: new language
