Repository nvim-treesitter/nvim-treesitter, pull requests merged in 2024-12, with the labels that each got.

#7434 Add circom highlights
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/circom/folds.scm
  queries/circom/highlights.scm
  queries/circom/injections.scm
  queries/circom/locals.scm
Labels: new language

#7277 feat(ipkg): add parser and queries
  README.md
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/ipkg/folds.scm
  queries/ipkg/highlights.scm
  queries/ipkg/indents.scm
  queries/ipkg/injections.scm
  queries/ipkg/locals.scm
Labels: needs response, new language

#7503 fix(xml): properly indent closing tags
  queries/xml/indents.scm
Labels: indent
