Repository nvim-treesitter/nvim-treesitter, pull requests merged in 2024-04, with the labels that each got.

#6381 feat(roc): add new parser tree-sitter-roc
  README.md
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/roc/highlights.scm
  queries/roc/injections.scm
  queries/roc/locals.scm
Labels: new language

#6402 fix(rust): indentation in multi-line tuple pattern
  queries/rust/indents.scm
  tests/indent/rust/tuple.rs
Labels: indent

#6395 add earthfile language
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/earthfile/highlights.scm
  queries/earthfile/injections.scm
Labels: new language

#6428 feat(wit): Add wit parser
  README.md
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/wit/highlights.scm
  queries/wit/injections.scm
Labels: new language

#6476 feat!: add explicit path field to parser info
  lua/nvim-treesitter/install.lua
  lua/nvim-treesitter/parsers.lua
  runtime/queries/rust/indents.scm
Labels: NEXT
