Repository nvim-treesitter/nvim-treesitter, pull requests merged in 2024-03, with the labels that each got.

#6050 feat: gotemplate and helm grammar
  README.md
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/gotmpl/highlights.scm
  queries/gotmpl/injections.scm
  queries/helm/highlights.scm
  queries/helm/injections.scm
Labels: new language

#6261 feat: add vento support
  README.md
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/vento/highlights.scm
  queries/vento/injections.scm
Labels: new language

#6245 feat: add just parser
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/just/folds.scm
  queries/just/highlights.scm
  queries/just/indents.scm
  queries/just/injections.scm
  queries/just/locals.scm
Labels: needs response, new language

#6327 feat: add djot support
  lua/nvim-treesitter/parsers.lua
  queries/djot/highlights.scm
  queries/djot/injections.scm
Labels: new language

#6359 feat(liquid): add new parser tree-sitter-liquid
  README.md
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/liquid/highlights.scm
  queries/liquid/injections.scm
Labels: new language

#6379 feat(snakemake): add indentation queries
  queries/snakemake/indents.scm
Labels: indent
