Repository nvim-treesitter/nvim-treesitter, pull requests merged in 2024-07, with the labels that each got.

#6810 Feat: Pro(b)log support
  README.md
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/problog/folds.scm
  queries/problog/highlights.scm
  queries/problog/indents.scm
  queries/problog/injections.scm
  queries/prolog/folds.scm
  queries/prolog/highlights.scm
  queries/prolog/indents.scm
  queries/prolog/injections.scm
Labels: new language

#6855 feat: editorconfig parser and queries
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/editorconfig/folds.scm
  queries/editorconfig/highlights.scm
  queries/editorconfig/injections.scm
Labels: new language

#6875 feat(goctl): add goctl language support.
  README.md
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/goctl/folds.scm
  queries/goctl/highlights.scm
  queries/goctl/injections.scm
Labels: new language

#6878 feat: tree-sitter-nginx
  README.md
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/nginx/folds.scm
  queries/nginx/highlights.scm
  queries/nginx/injections.scm
Labels: new language

#6925 feat(vhdl): Add VHDL support
  README.md
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/vhdl/folds.scm
  queries/vhdl/highlights.scm
  queries/vhdl/injections.scm
Labels: new language

#6698 feat(latex): update delimiter capture (#6697)
  lockfile.json
  queries/latex/highlights.scm
Labels: upstream parser

#6950 feat(powershell): add parser and queries
  README.md
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/powershell/folds.scm
  queries/powershell/highlights.scm
  queries/powershell/indents.scm
  queries/powershell/injections.scm
  queries/powershell/locals.scm
Labels: new language

#6671 feat: rescript parser and queries
  README.md
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/rescript/folds.scm
  queries/rescript/highlights.scm
  queries/rescript/indents.scm
  queries/rescript/injections.scm
  queries/rescript/locals.scm
  tests/indent/rescript/basic.res
  tests/indent/rescript/complex.res
  tests/indent/rescript/conditional.res
  tests/indent/rescript_spec.lua
Labels: upstream parser, new language

#6997 Add VRL support for nvim-treesitter
  README.md
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/vrl/folds.scm
  queries/vrl/highlights.scm
  queries/vrl/indents.scm
  queries/vrl/injections.scm
  queries/vrl/locals.scm
Labels: new language

#6998 fix(r): prevent double indent from pipes
  queries/r/indents.scm
  tests/indent/r/incomplete_pipe.R
  tests/indent/r_spec.lua
Labels: indent
