Repository nvim-treesitter/nvim-treesitter, pull requests merged in 2025-02, with the labels that each got.

#7545 feat: add razor
  README.md
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/razor/folds.scm
  queries/razor/highlights.scm
  queries/razor/injections.scm
Labels: new language

#7626 feat: add enforce
  README.md
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/enforce/folds.scm
  queries/enforce/highlights.scm
  queries/enforce/indents.scm
  queries/enforce/injections.scm
  queries/enforce/locals.scm
Labels: new language

#7573 feat(jinja2): add jinja2
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/jinja/highlights.scm
  queries/jinja/injections.scm
  queries/jinja_inline/highlights.scm
  queries/jinja_inline/injections.scm
Labels: new language

#7649 feat(gomod): support `tool`
  queries/gomod/highlights.scm
Labels: needs response

#7615 fix(gleam): indent on unqualified imports rather than import
  queries/gleam/indents.scm
Labels: indent

#7657 feat: added tree-sitter-kcl
  lockfile.json
  lua/nvim-treesitter/parsers.lua
  queries/kcl/folds.scm
  queries/kcl/highlights.scm
  queries/kcl/injections.scm
Labels: new language
